### ISSUE TITLE
Lien pour ta partie de recherche

### ISSUE THREAD

**Issue by lotus-prog** [master-csmi/software-project-management-projet-kanban#3]
Peux-tu m'envoyer plusieurs de tes liens de recherche sur Kanban (lien https) afin d'éviter la redondance des informations sur nos parties mais également de vérifier la véracité des informations.
Je te remercie,
Quentin Dumont

**Comment by mgrigoryan9** [comment]
Le lien que je t’ai envoyé sur fb est celui que j’ai utilisé pour ma partie. 
Et juste après ce paragraphe il y a la suite que je pensais pourrais t’être utile. 
J’ai fait un slide dessus que j’ai enregistré sur kanban.tex
